---
title: "Getting Twitter data for topic modeling lecture"
author: "Thomas Davidson"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
# The following lines define how the output of code chunks should behave
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(include = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(error = TRUE)

# Required packages
library(rmarkdown)
library(tidyverse)
library(rtweet)
library(jsonlite)
```

Loading credentials
```{r q1, echo=TRUE, tidy=TRUE, eval=FALSE}
creds <- read_json("creds.json") # load credentials

# authenticate via web browser
token <- create_token( 
  app = "RUCompSoc",
  consumer_key = creds$key,
  consumer_secret = creds$secret)
```

Getting 2000 most recent statuses for NYTimes and WSJ.
```{r q6, echo=TRUE, tidy=TRUE}
tl <- get_timeline(c("nytimes", "wsj"), n = 2000)
### Your code here
tl <- tl %>% select(status_id, created_at, screen_name, text, favorite_count, retweet_count)
tl$status_id <- as.character(tl$status_id) # Convert IDs to string
write_tsv(tl, "../data/nytimes_wsj_2000_statuses_oct2521.tsv")
```
